### ISSUE TITLE
Provide access to additional search paths

### ISSUE THREAD

**Issue by bobatkey** [stedolan/malfunction#13]
Malfunction is currently restricted to looking up identifiers on the standard OCaml search path, which limits malfunction programs to only accessing the standard library. It would be nice to be able to provide additional search paths to other .cmi files.

Extra nice would be ocamlfind integration.

**Comment by stedolan** [comment]
Apologies that it's taken me so long to respond! This is a very sensible feature request, which it's taking far too long for me to find time for.

**Comment by yforster** [comment]
I'd like to second this feature request :) We are basically done verifying extraction from Coq to Malfunction. Now to link with other OCaml libraries (e.g. with the OCaml implementation of Coq's primitive integers) being able to use an additional search path would be needed.

**Comment by yforster** [comment]
At least for our use case, this was covered by #35 now

**Comment by stedolan** [comment]
Closing, then, but reopen if #35 doesn't cover other uses.
