### ISSUE TITLE
Continuations

### ISSUE THREAD

**Issue by Mathnerd314** [stedolan/malfunction#14]
During the talk, you mentioned a "type system which will solve the world's programming problems forever, unifying every possible type of language feature into one grand abstraction", and presented a slide showing "Higher-kinded dependently-typed GOTO".

But Malfunction doesn't have continuations, just lambdas. You can't even write GOTO, much less COMEFROM. Furthermore it seems like continuations are an elegant way to [unify eager and lazy programming](https://www.microsoft.com/en-us/research/wp-content/uploads/2006/01/not-not-ml.pdf). 

My point here is that while OCaml [doesn't support continuations](http://www.cs.cornell.edu/courses/cs3110/2011sp/recitations/rec26-cps/cps.htm), [SML/NJ](http://www.smlnj.org/) does. I guess it's a little slower than OCaml, but not by much (7.8 vs 9.3 seconds in a [toy benchmark](https://thebreakfastpost.com/2015/05/10/sml-and-ocaml-so-why-was-the-ocaml-faster/)).

**Comment by stedolan** [comment]
I'm not quite sure what you're suggesting / asking for. Do you want Malfunction to be retargeted to SML/NJ? I'm unfamiliar with SML/NJ's internals, does it have an untyped intermediate representation before closure conversion? Regardless, I think that would be a separate project.

Speaking of continuations, Malfunction / OCaml is unlikely to ever have call/cc. [There are good reasons to avoid it!](http://okmij.org/ftp/continuations/against-callcc.html). We're [working on](https://github.com/ocamllabs/ocaml-multicore) adding delimited continuations / algebraic effects to OCaml, which will hopefully show up in Malfunction eventually.

**Comment by Mathnerd314** [comment]
> Do you want Malfunction to be retargeted to SML/NJ? I'm unfamiliar with  SML/NJ's internals, does it have an untyped intermediate representation  before closure conversion? Regardless, I think that would be a separate  project. 

I'm not that familiar with SML/NJ either, but I think it has a structured compilation pipeline. I guess I will poke around to find someone else more knowledgeable on that subject.

> Speaking of continuations, Malfunction / OCaml is unlikely to ever have call/cc. There are good reasons to avoid it!. We're working on adding delimited continuations / algebraic effects to OCaml, which will hopefully show up in Malfunction eventually.

I was using continuations in the sense of the "Haskell is not not ML" [paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2006/01/not-not-ml.pdf), which I guess is a rather non-standard definition. Its continuations are a sort of zero-argument lambda, that is guarantee to never produce a value, and where the type of the continuation specifies the expected layout of the stack/heap. 

The question I had boils down to whether there's anything like those continuations in the OCaml compilation pipeline, that maybe Malfunction could expose, or if it's necessary to write yet another closure conversion library to experiment with the paper's continuations.

**Comment by stedolan** [comment]
OCaml has nothing directly comparable to the continuations / negation types in the paper you linked, but I suspect you could simulate them by implementing ~T as functions from T to some abstract result type.
