### ISSUE TITLE
Dependency issues with ocaml 4.07.0+flambda

### ISSUE THREAD

**Issue by xekoukou** [stedolan/malfunction#16]
opam cannot find a solution so as to install malfunction.

**Comment by stedolan** [comment]
The released version doesn't support 4.07 yet. The master branch does, as of now, so you should be able to build it locally.

**Comment by xekoukou** [comment]
Nice, [one](https://github.com/dbuenzli/uunf) of the libraries I use has some installation problems with 4.05.0. I hope this will fix them:
