### ISSUE TITLE
zero argument functions - Difference between Interpreted and Compiled Code.

### ISSUE THREAD

**Issue by xekoukou** [stedolan/malfunction#17]
There is a difference between the interpreter(1) and the Compiler in handling zero argument functions.

[1.](https://github.com/stedolan/malfunction/blob/master/src/malfunction_interpreter.ml#L45)

Updated the comment to only report the inconsistency.

**Comment by stedolan** [comment]
Zero argument functions aren't supported. Functions are curried, so a two-argument function is actually a curried function `'a -> 'b -> 'c`. A zero-argument function would just be a value.

b2802dbd88210f76f994d8ee11662501a21a81a0 removes some confusion by making zero-argument lambdas and applications a syntax error.

As of very recently, Malfunction supports `(lazy ...)` and `(force ...)`, which are a better way of representing thunks.
