### ISSUE TITLE
Missing installation step

### ISSUE THREAD

**Issue by olleharstedt** [stedolan/malfunction#2]
Hi!

Maybe you can add a missing installation step in the README, between opam install and `malfunction compile ...`? Like `ocamlbuild -use-findlib` or however you do it. Also, for me, it was not added to ocamlfind when I did the opam pin and installation, had to do it manually.

Regards
Olle

**Comment by stedolan** [comment]
I use malfunction via an opam pin. What went wrong using pinning for you,
exactly? Did malfunction install successfully? Was the `malfunction` binary
available afterwards?

**Comment by olleharstedt** [comment]
I did a git clone, pinned the local folder and did opam update, opam upgrade. Installed without problem, but saw no malfunction binary.

**Comment by olleharstedt** [comment]
Ah, yes, there is a binary there.

Yep, did the config env.
