### ISSUE TITLE
Support for OCaml > 4.09?

### ISSUE THREAD

**Issue by anton-trunov** [stedolan/malfunction#27]
Are there any plans to support the recent versions of OCaml? If not, could you please estimate how hard it could be to upgrade Malfunction? (given the lack of previous experience with OCaml compiler hacking).

**Comment by stedolan** [comment]
Yep, definitely planning to support recent versions. At this point, I'll probably wait until the (imminent) release of 4.12 and then do 4.10-4.12 together.

Supporting a new version is generally not much code (e.g. [here's the 4.09 patch](https://github.com/stedolan/malfunction/commit/b2b4f8ad6b50978579f34aafdbbfed8888070bd5)), but it does require some familiarity with the OCaml compiler's layout.

**Comment by anton-trunov** [comment]
Awesome! Thanks for sharing your plans. And indeed the size of the 4.09 patch looks very reasonable. Looking forward to the upgrade.

**Comment by stedolan** [comment]
4.10 / 4.11 / 4.12 work now.

**Comment by anton-trunov** [comment]
Thanks so much! Could you tag it as a new release, please? I can then give you a hand with a PR to opam-repository if you don't mind.
