### ISSUE TITLE
Some bug with `Verbose` option

### ISSUE THREAD

**Issue by sloboegen** [stedolan/malfunction#30]
When I use `Malfunction_compiler.compile_and_load` with ```[`Verbose]``` flag I get the following error:
```
Fatal error: exception Unix.Unix_error(Unix.ENOTEMPTY, "rmdir", "/tmp/malfunction46896e.tmp")
```
It works fine without this option. This error appears every time I use this flag. In particular, you can call with `verbose` option in `compile_and_load` from `examples/primrec.ml` and get the same error.

**Comment by stedolan** [comment]
Fixed, it was leaving too many temporary files in `/tmp`. (I've disabled the inlining report & asm output for `Verbose`, because there's no good way to get it at the moment)
