### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by mattam82** [stedolan/malfunction#41]
We would like to have a new release including PR #38 (we can take care of opam packaging if you like, and don't need ocaml 5 support), so as to release https://github.com/yforster/coq-malfunction on opam.

**Comment by mattam82** [comment]
@stedolan ?

**Comment by mattam82** [comment]
Ping @stedolan , we'd like to get a first release out
https://github.com/yforster/coq-verified-extraction/releases/tag/v0.9-8.19

**Comment by stedolan** [comment]
Got there eventually! v0.6: https://github.com/ocaml/opam-repository/pull/26134
