### ISSUE TITLE
Mixed mutable and immutable fields

### ISSUE THREAD

**Issue by DemiMarie** [stedolan/malfunction#7]
Some OCaml code uses mixed mutable and immutable blocks, such as this:

``` ocaml
type q = { x : int; mutable y : int; }
```

It would be useful for Malfunction to support this.

**Comment by chambart** [comment]
The OCaml backend does not in fact. this would be compiled as a whole mutable block.

**Comment by stedolan** [comment]
> The OCaml backend does not in fact. this would be compiled as a whole mutable block.

In that case, I'll close this issue. Malfunction code can make do with blocks (wholly immutable) and vectors (wholly mutable).
